// SPDX-License-Identifier: Apache-2.0

use std::{
  any::{Any, TypeId},
  collections::HashMap,
  fmt::Debug,
};

use rustc_hash::FxHashMap;

#[macro_export]
macro_rules! actions {
  (
    $namespace: literal,
    [$(
      $(#[$meta:meta])?
      $ident:ident
    ),*$(,)?]
  ) => {
    $(
      #[cfg_attr(debug_assertions, derive(::core::fmt::Debug))]
      #[derive(::core::clone::Clone, ::core::marker::Copy)]
      #[derive(::core::cmp::PartialEq, ::core::cmp::Eq)]
      #[derive(::core::hash::Hash)]
      #[derive(::core::default::Default)]
      $(#[$meta])?
      pub struct $ident;
      impl $crate::action::Action for $ident {
        fn name(&self) -> &'static str {
          concat!($namespace, "::", stringify!($ident))
        }
        fn debug() -> &'static str {
          concat!($namespace, "::", stringify!($ident))
        }
        fn build(_: $crate::private::toml::Value) -> anyhow::Result<::std::boxed::Box<dyn $crate::action::Action>> {
          Ok(::std::boxed::Box::new(Self))
        }
      }
      impl $ident {
        fn __autogenerated() {
          fn __builder() -> $crate::action::MacroActionData {
            $crate::action::MacroActionData {
              name: <$ident as $crate::action::Action>::debug(),
              type_id: ::core::any::TypeId::of::<$ident>(),
              build: <$ident as $crate::action::Action>::build
            }
          }

          $crate::private::inventory::submit! {
            $crate::action::MacroActionBuilder(__builder)
          }
        }
      }
    )*
  };
  (
    [$(
      $(#[$meta:meta])?
      $ident:ident
    ),*$(,)?]
  ) => {
    $(
      #[cfg_attr(debug_assertions, derive(::core::fmt::Debug))]
      #[derive(::core::clone::Clone, ::core::marker::Copy)]
      #[derive(::core::cmp::PartialEq, ::core::cmp::Eq)]
      #[derive(::core::hash::Hash)]
      #[derive(::core::default::Default)]
      $(#[$meta])?
      pub struct $ident;
      impl $crate::action::Action for $ident {
        fn name(&self) -> &'static str {
          stringify!($ident)
        }
        fn debug() -> &'static str {
          stringify!($ident)
        }
        fn build(_: $crate::private::toml::Value) -> anyhow::Result<::std::boxed::Box<dyn $crate::action::Action>> {
          Ok(::std::boxed::Box::new(Self))
        }
      }
      impl $ident {
        fn __autogenerated() {
          fn __builder() -> $crate::action::MacroActionData {
            $crate::action::MacroActionData {
              name: <$ident as $crate::action::Action>::debug(),
              type_id: ::core::any::TypeId::of::<$ident>(),
              build: <$ident as $crate::action::Action>::build
            }
          }

          $crate::private::inventory::submit! {
            $crate::action::MacroActionBuilder(__builder)
          }
        }
      }
    )*
  };
}

actions! {
  [
    NoAction,
    Quit,
  ]
}

pub struct MacroActionBuilder(pub fn() -> MacroActionData);
inventory::collect!(MacroActionBuilder);
pub struct MacroActionData {
  pub name: &'static str,
  pub type_id: TypeId,
  pub build: ActionBuilder,
}
type ActionBuilder = fn(json: toml::Value) -> anyhow::Result<Box<dyn Action>>;

#[derive(Debug)]
struct ActionData {
  pub build: ActionBuilder,
}

#[derive(Debug)]
pub struct ActionRegistry {
  by_name: HashMap<&'static str, ActionData>,
  names: Vec<&'static str>,
  names_by_type_id: FxHashMap<TypeId, &'static str>,
}
impl ActionRegistry {
  pub fn new() -> Self {
    let mut this = Self {
      by_name: HashMap::default(),
      names: Vec::default(),
      names_by_type_id: FxHashMap::default(),
    };
    for builder in inventory::iter::<MacroActionBuilder> {
      let action = (builder.0)();
      this.insert_action(action);
    }

    this
  }

  fn insert_action(&mut self, action: MacroActionData) {
    let name = action.name;
    if self.by_name.contains_key(name) {
      panic!("Action with name `{name}` already registered");
    };
    self.by_name.insert(
      name,
      ActionData {
        build: action.build,
      },
    );
    self.names_by_type_id.insert(action.type_id, name);
    self.names.push(name);
  }

  pub fn get_by_name(&self, name: &str) -> Box<dyn Action> {
    self
      .by_name
      .get(name)
      .map(|b| (b.build)(toml::Value::String("()".to_string())).unwrap())
      .unwrap_or(Box::new(NoAction))
    // .unwrap()
  }
}
impl Default for ActionRegistry {
  fn default() -> Self {
    Self::new()
  }
}

pub trait Action: Any {
  fn name(&self) -> &'static str;
  fn debug() -> &'static str
  where
    Self: Sized;
  fn build(value: toml::Value) -> anyhow::Result<Box<dyn Action>>
  where
    Self: Sized;
}
impl dyn Action {
  #[inline]
  pub fn as_any(&self) -> &dyn Any {
    self
  }
}
impl Debug for dyn Action {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.debug_tuple("dyn Action")
      .field(&self.name())
      .finish_non_exhaustive()
  }
}
